//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentRepoAPI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventHistory
    {
        public long EventId { get; set; }
        public int EventType { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
