//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentRepoAPI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folders
    {
        public Nullable<long> ParentId { get; set; }
        public long FolderId { get; set; }
        public string FolderName { get; set; }
        public string FolderUrl { get; set; }
        public bool ReadAccess { get; set; }
        public bool ModifyAccess { get; set; }
        public bool DeleteAccess { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
