//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentRepoAPI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedFolders
    {
        public long SharedFoldersId { get; set; }
        public int SharedFolders1 { get; set; }
        public int SharedBy { get; set; }
        public int SharedTo { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
