//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentRepoAPI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long UserId { get; set; }
        public string EmailId { get; set; }
        public string PasswordHash { get; set; }
        public int UserTypeId { get; set; }
        public bool UserActive { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RecoveryPhoneNum { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
